### PR TITLE
Fixed kerberos keytab attribute name in defaults

### PR DESCRIPTION
**Pull request by bbaugher**

### CODE REVIEW

**Comment by noslowerdna** [comment]
+1

**Comment by mkwhitacre** [comment]
+1 to fix.  -1 to breaking Travis build.

**Comment by bbaugher** [comment]
That should be fixed with https://github.com/cerner/cerner_kafka/pull/60. Specifically this change here, https://github.com/cerner/cerner_kafka/pull/60/commits/622ea0740c9d66c9cbb4bb5f6bf21dc7f6a9f644

**Comment by mkwhitacre** [comment]
Merging with the assumption that if Travis doesn't get fixed you'll open a new issue.

**Pull request merged**
