### PR TITLE
I've encountered some issues on the shell scripts with this cookbook. Here are my proposed fix and improvements

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Comment by mkwhitacre** [comment]
@henri-tremblay  thanks for the PR, for anyone who stumbles on this PR later, can you elaborate on the issues you encountered and how the problems manifested?  Will help to identify this being a fix for problems in case someone encounters it in the future.

**Comment by henri-tremblay** [comment]
Sure. 
* Originally, the problem was the double square-brackets in some if. I've noticed you already have fixed some since the last release. But some were still there. They don't work on a classical Ubuntu shell
* Then, the code was badly indented because of tabs. You also have fixed some of these but I've removed the last pending tabs
* Finally, just to nicely pass automated shell verification tools, I've changed some other little things like replacing back-quotes by $(), adding double-quotes and some parenthesis that were not needed to do arithmetic on variables

**Comment by bbaugher** [comment]
+1

**Comment by mkwhitacre** [comment]
+1  Merging.

**Comment by bbaugher** [comment]
@henri-tremblay do you mind opening a pull request to add yourself as a [contributor](https://github.com/cerner/cerner_kafka/blob/master/CONTRIBUTORS.txt).

**Pull request merged**
