### PR TITLE
#14: Removed default kafka configs

### PR DESCRIPTION
**Pull request by bbaugher**

### CODE REVIEW

**Comment by mkwhitacre** [comment]
+1 to the changes but might warrant a version bump since consumers will need to update more than their config to consume.

**Comment by bbaugher** [comment]
Are you think 2.0.0?

**Comment by mkwhitacre** [comment]
Not sure.  The fact that upgrading to this version would result in their server.properties no longer being generated the same and seems like potentially surprising behavior (and could result in unexpected data loss since stuff like retention policy would be decreased)

So yeah am thinking that 2.0 might be a reasonable jump.

**Comment by bbaugher** [comment]
Bumped to 2.0.0

**Comment by bbaugher** [comment]
Updated README about server properties defaults, https://github.com/cerner/cerner_kafka/commit/47f8d37b2d05b8cf5db76ebc1ff25f2381f97111

**Comment by noslowerdna** [comment]
+1

**Comment by mkwhitacre** [comment]
+1

**Comment by bbaugher** [comment]
Got enough +1s, merging

**Pull request merged**
