### PR TITLE
#49: Added attributes for providing options for offset monitor

### PR DESCRIPTION
**Pull request by bbaugher**

### CODE REVIEW

**Comment by EdwardSkoviak** [comment]
including the "--" in the key's value looks a little awkward. i suppose we'd lose the ability to provide shorthand if we hardcoded prepending "--" to each option, but doesn't seem like we'd really be losing anything. any reason you decided not to do that?

**Comment by asandwich** [comment]
+1

**Comment by bbaugher** [comment]
I wanted to make as few assumptions as possible and just provide raw input in hope that is fairly flexible but still readable

**Comment by EdwardSkoviak** [comment]
fair enough, +1 as well

**Comment by bbaugher** [comment]
Got enough +1s, merging

**Pull request merged**
