### PR TITLE
#12 Added zookeeper_chroot attribute & #11 Added code to create zookeeper chroot

### PR DESCRIPTION
**Pull request by bbaugher**

### CODE REVIEW

**Comment by mkwhitacre** [comment]
Minor doc nit otherwise +1

**Comment by bbaugher** [comment]
Updated doc, https://github.com/cerner/cerner_kafka/commit/e3800313e6ee9af8a718a9f19334e1ea7ec0cad4

**Comment by bbaugher** [comment]
Given 0.8.2 of Kafka creates its zookeeper chroot, I'm assuming we don't need to do it here anymore correct?

**Comment by mkwhitacre** [comment]
Yeah probably don't need this enhancement.  Still might be worthwhile to have the doc update for if not specified.

**Comment by bbaugher** [comment]
Closing this and putting out a new pull with just the zookeeper chroot attribute changes (no automatic zk chroot creation).

**Pull request closed without merging**
