### PR TITLE
Add myself to CONTRIBUTORS.txt

### PR DESCRIPTION
**Pull request by pradeepbhadani**
@bbaugher  Added myself to contributor list.

### CODE REVIEW

**Comment by bbaugher** [comment]
@pradeepbhadani looks like your pull didn't quite work like we thought. You will need to re-base or start over

**Comment by pradeepbhadani** [comment]
@bbaugher  I tried to resolve conflicts and added myself to Contributor.txt

**Comment by bbaugher** [comment]
This still includes a number of additional changes. It might be best to pull the latest master branch and start from there

**Comment by pradeepbhadani** [comment]
I pulled the latest master branch and then removed conflicts. 
I am not sure why this happening and i am not able to see any additional changes in pull request.

It might be good you reject this pull request and add my name in contributor.txt

**Comment by bbaugher** [comment]
I did this with this commit, https://github.com/cerner/cerner_kafka/commit/b7fc3520d694367b8d35ef01f9ad59324cc98f04

**Comment by pradeepbhadani** [comment]
Thanks.

**Pull request closed without merging**
